spring:
  datasource:
    core:
      url: jdbc:postgresql://localhost:5432/
      jdbcUrl: jdbc:postgresql://localhost:5432/
      username: postgres
      password: 123456
      driver-class-name: org.postgresql.Driver
    mb:
      url: jdbc:postgresql://localhost:5432/
      jdbcUrl: jdbc:postgresql://localhost:5432/
      username: postgres
      password: 123456
      driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379
      password:
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  jmx:
    enabled:
      false


app:
  web:
    host: localhost
    port: 3000

  server:
    host: localhost
    port: 8080

musicbrainz:
  release-url: https://musicbrainz.org/ws/2/release-group/?query=release:%s&fmt=json



#
#  cache:
#    type: redis
#    redis:
#      host: localhost
#      port: 6379
#      password:
#      lettuce:
#        pool:
#          max-active: 8
#          max-idle: 8
#          min-idle: 0
